plugins {
	 id 'net.fabricmc.fabric-loom' version "${loom_version}"
	 id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()

	maven {
		name = 'Fabric'
		url = 'https://maven.fabricmc.net/'
	}

	maven {
		url = 'https://maven.imyvm.org'
	}

	maven {
		url = uri('https://maven.pkg.github.com/ImyvmCircle/ImyvmEconomy')
		credentials {
			username = System.getenv('GITHUB_USERNAME')
			password = System.getenv('GITHUB_TOKEN')
		}
		content {
			includeModule 'com.imyvm', 'imyvm-economy'
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	implementation "com.imyvm:imyvm-economy:${project.imyvm_economy_version}"
	implementation "com.imyvm:imyvm-hoki:${project.imyvm_hoki_version}"
	implementation "org.xerial:sqlite-jdbc:${project.sqlite_jdbc_version}"
	include "org.xerial:sqlite-jdbc:${project.sqlite_jdbc_version}"
}

processResources {
	inputs.property 'version', project.version

	filesMatching('fabric.mod.json') {
		expand 'version': project.version
	}
}

tasks.register("financeSelfTest", JavaExec) {
	dependsOn testClasses
	classpath = sourceSets.test.runtimeClasspath
	mainClass = "com.imyvm.finance.FinanceSelfTest"
}

test {
	dependsOn financeSelfTest
	failOnNoDiscoveredTests = false
}

tasks.withType(JavaCompile).configureEach {
	options.release = 25
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}

	withSourcesJar()
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
		maven {
			url = 's3://imyvm-maven-repository'
			credentials(AwsCredentials) {
				accessKey = System.getenv("S3_ACCESS_KEY_ID")
				secretKey = System.getenv("S3_SECRET_ACCESS_KEY")
			}
		}
		}
	}
