org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=false

systemProp.org.gradle.s3.endpoint=https://v8j1.or1.idrivee2-63.com

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.17
fabric_version=0.155.2+26.2

# Mod Properties
mod_version=1.0.1
maven_group=com.imyvm
archives_base_name=imyvm-finance

# Dependencies
imyvm_economy_version=26.2-1.2.7
imyvm_hoki_version=1.1.6
sqlite_jdbc_version=3.51.1.1
