org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.17
fabric_version=0.155.2+26.2

# Mod Properties
mod_version=26.2-0.1.0
maven_group=com.imyvm
archives_base_name=imyvm-finance

# Dependencies
imyvm_economy_version=26.2-1.2.7
